
#define	TID_ADD_COMPLEX_INSTRUMENT                       0		// < AddComplexInstrument (Add Complex Instrument)
#define	TID_AUCTION_BBO                                  1		// < AuctionBBO (Auction Best Bid/Offer)
#define	TID_AUCTION_CLEARING_PRICE                       2		// < AuctionClearingPrice (Auction Clearing Price)
#define	TID_CROSS_REQUEST                                3		// < CrossRequest (Cross Request)
#define	TID_EXECUTION_SUMMARY                            4		// < ExecutionSummary (Execution Summary)
#define	TID_FULL_ORDER_EXECUTION                         5		// < FullOrderExecution (Full Order Execution)
#define	TID_HEARTBEAT                                    6		// < Heartbeat (Heartbeat)
#define	TID_INSTRUMENT_STATE_CHANGE                      7		// < InstrumentStateChange (Instrument State Change)
#define	TID_INSTRUMENT_SUMMARY                           8		// < InstrumentSummary (Instrument Summary)
#define	TID_ORDER_ADD                                    9		// < OrderAdd (Order Add)
#define	TID_ORDER_DELETE                                10		// < OrderDelete (Order Delete)
#define	TID_ORDER_MASS_DELETE                           11		// < OrderMassDelete (Order Mass Delete)
#define	TID_ORDER_MODIFY                                12		// < OrderModify (Order Modify)
#define	TID_ORDER_MODIFY_SAME_PRIO                      13		// < OrderModifySamePrio (Order Modify Same Priority)
#define	TID_PACKET_HEADER                               14		// < PacketHeader (Packet Header)
#define	TID_PARTIAL_ORDER_EXECUTION                     15		// < PartialOrderExecution (Partial Order Execution)
#define	TID_PRODUCT_STATE_CHANGE                        16		// < ProductStateChange (Product State Change)
#define	TID_PRODUCT_SUMMARY                             17		// < ProductSummary (Product Summary)
#define	TID_QUOTE_REQUEST                               18		// < QuoteRequest (Quote Request)
#define	TID_SNAPSHOT_ORDER                              19		// < SnapshotOrder (Snapshot Order)
#define	TID_TOP_OF_BOOK                                 20		// < TopOfBook (Top of Book)
#define	TID_TRADE_REPORT                                21		// < TradeReport (Trade Report)
#define	TID_TRADE_REVERSAL                              22		// < TradeReversal (Trade Reversal)
